apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: globalbitcoincash-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - www.globalbitcoin.cash
    - globalbitcoin.cash
    secretName: globalbitcoincash-tls
  defaultBackend:
    service:
      name: globalbitcoincash
      port:
        number: 107
  rules:
  - host: globalbitcoin.cash
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: globalbitcoincash
            port:
              number: 107
  - host: www.globalbitcoin.cash
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: globalbitcoincash
            port:
              number: 107
